
name: auto-docking
dependencies:
  - python=3.6.6
  - pip==20.0.2
  - pip:
    - ipython
    - bokeh
    - TensorFlow==1.12.0
    - numpy==1.18.1
    - gym==0.15.4
    - joblib==0.17.0
    - runstats==1.8.0
    - pandas==1.1.3
    - psutil==5.7.2
    - tqdm==4.50.0
    - matplotlib==3.3.2
    - mpi4py==3.0.3
    - scipy==1.5.2
    - shap==0.36.0
    - opencv-python==4.4.0.44
    - -e .
    

